


































































































































































































































































d: 0.0544; g: 3.0455; r1: 0.0071; path: 0.0008; mean path: 0.1292; augment: 0.0050:   0% 257/800000 [14:18<742:12:41,  3.34s/it]
Traceback (most recent call last):
  File "train.py", line 559, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 194, in train
    d_loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/content/drive/My Drive/Colab Notebooks/stylegan2-pytorch/op/upfirdn2d.py", line 143, in backward
    ctx.out_size,
  File "/content/drive/My Drive/Colab Notebooks/stylegan2-pytorch/op/upfirdn2d.py", line 42, in forward
    g_pad_y1,
RuntimeError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 15.90 GiB total capacity; 11.62 GiB already allocated; 101.75 MiB free; 14.98 GiB reserved in total by PyTorch)